# Generated by Django 2.2.5 on 2019-10-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('end_date', models.DateField()),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('end_date', models.DateField()),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SmallTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('end_date', models.DateField()),
                ('flag', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.MiddleTask')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('end_date', models.DateField()),
                ('flag', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ProjectManagement')),
            ],
        ),
        migrations.AddField(
            model_name='middletask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ProjectTask'),
        ),
    ]
