# Generated by Django 2.1.1 on 2019-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('big_task', models.IntegerField()),
                ('end_task', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
