# Generated by Django 2.2.5 on 2019-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20191005_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middletask',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smalltask',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
