# Generated by Django 2.1.1 on 2019-09-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190916_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
