# Generated by Django 2.2.5 on 2019-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20191008_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='middletask',
            name='update_flag_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='update_flag_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='update_flag_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smalltask',
            name='update_flag_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
