# Generated by Django 2.1.1 on 2019-09-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190916_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('middle_task_name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('end_task', models.DateField()),
                ('middle_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ProjectTask')),
            ],
        ),
    ]
