# Generated by Django 2.1.1 on 2019-09-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20190919_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('small_task_name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('end_date', models.DateField()),
                ('small_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.MiddleTask')),
            ],
        ),
    ]
