# Generated by Django 2.1.1 on 2019-09-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_smalltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='middletask',
            name='middle_task_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='project_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='big_task_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smalltask',
            name='small_task_flag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
