# Generated by Django 2.2.5 on 2019-10-03 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('next_action', models.TextField(blank=True)),
                ('related_hash', models.CharField(blank=True, max_length=50)),
                ('day', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
