# Generated by Django 2.1.1 on 2019-02-23 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
