# Generated by Django 2.1.1 on 2019-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0002_auto_20190223_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(),
        ),
    ]
