# Generated by Django 2.1.1 on 2019-03-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0003_auto_20190224_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='related_hash',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
