# Generated by Django 2.1.1 on 2019-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0003_auto_20190224_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hash_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
