# Generated by Django 2.1.1 on 2019-05-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0004_document_related_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='next_action',
            field=models.TextField(blank=True),
        ),
    ]
