# Generated by Django 2.1.1 on 2019-02-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0004_document_hash_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='hash_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
